package megvii.testfacepass.independent.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import megvii.testfacepass.independent.bean.DeliveryRecord;
import megvii.testfacepass.independent.bean.DustbinBean;
import megvii.testfacepass.independent.bean.UserMessage;

import megvii.testfacepass.independent.bean.DeliveryRecordDao;
import megvii.testfacepass.independent.bean.DustbinBeanDao;
import megvii.testfacepass.independent.bean.UserMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deliveryRecordDaoConfig;
    private final DaoConfig dustbinBeanDaoConfig;
    private final DaoConfig userMessageDaoConfig;

    private final DeliveryRecordDao deliveryRecordDao;
    private final DustbinBeanDao dustbinBeanDao;
    private final UserMessageDao userMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deliveryRecordDaoConfig = daoConfigMap.get(DeliveryRecordDao.class).clone();
        deliveryRecordDaoConfig.initIdentityScope(type);

        dustbinBeanDaoConfig = daoConfigMap.get(DustbinBeanDao.class).clone();
        dustbinBeanDaoConfig.initIdentityScope(type);

        userMessageDaoConfig = daoConfigMap.get(UserMessageDao.class).clone();
        userMessageDaoConfig.initIdentityScope(type);

        deliveryRecordDao = new DeliveryRecordDao(deliveryRecordDaoConfig, this);
        dustbinBeanDao = new DustbinBeanDao(dustbinBeanDaoConfig, this);
        userMessageDao = new UserMessageDao(userMessageDaoConfig, this);

        registerDao(DeliveryRecord.class, deliveryRecordDao);
        registerDao(DustbinBean.class, dustbinBeanDao);
        registerDao(UserMessage.class, userMessageDao);
    }
    
    public void clear() {
        deliveryRecordDaoConfig.clearIdentityScope();
        dustbinBeanDaoConfig.clearIdentityScope();
        userMessageDaoConfig.clearIdentityScope();
    }

    public DeliveryRecordDao getDeliveryRecordDao() {
        return deliveryRecordDao;
    }

    public DustbinBeanDao getDustbinBeanDao() {
        return dustbinBeanDao;
    }

    public UserMessageDao getUserMessageDao() {
        return userMessageDao;
    }

}
